### ISSUE TITLE
继承EasySwoole\Spl\SplBeanl的子类可能会导致定义的属性值丢失

### ISSUE THREAD

**Issue by ben-tan** [easy-swoole/spl#11]
file: src/SplBean.php
method: dataKeyMap()
result: 在dataKeyMap()方法时，可能会导致数组元素丢失
copy code:
final private function dataKeyMap(array $array): array
    {
        foreach ($this->setKeyMapping() as $dataKey => $beanKey) {
            if (array_key_exists($dataKey, $array)) {
                $array[$beanKey] = $array[$dataKey];
                unset($array[$dataKey]);
            }
        }
        return $array;
    }
analyze:
如果
        1.$array=['a' => 'apple', 'b' => 'bus'];
        2.$this->setKeyMapping() = ['a' => 'b'];
最终在方法体内return回来的数组只会剩下$array = ['b' => 'apple'];
$array['a']丢失了

**Comment by kiss291323003** [comment]
这是你自己错误用法额、、你都'a' => 'b'了
